### PR TITLE
Gimlet hangs on cold power-on after toolchain update

### LINKED ISSUE #1741: Gimlet hangs on cold power-on after toolchain update
Running Hubris after the toolchain bump (24bdff63d662053c097d6f84566bfae3ef772edd) has resulted in a Gimlet that doesn't come completely into A2 (resulting in screaming fans and general unpleasantness) -- but only on cold power-on.  From [a dump of the system](https://github.com/oxidecomputer/hubris/files/14910709/hubris.core.dead-gimlet.gz):

```
$ humility -d ./hubris.core.dead-gimlet tasks
humility: attached to dump
system time = 24221
ID TASK                       GEN PRI STATE    
 0 jefe                         0   0 recv, notif: fault timer(T+79)
 1 net                          1   5 recv, notif: eth-irq(irq61) wake-timer(T+276)
 2 sys                          0   1 recv, notif: exti-wildcard-irq(irq6/irq7/irq8/irq9/irq10/irq23/irq40)
 3 spi2_driver                  0   3 recv
 4 i2c_driver                   0   3 recv
 5 spd                          0   2 notif: i2c1-irq(irq31/irq32)
 6 packrat                      0   1 recv
 7 thermal                      0   5 wait: send to gimlet_seq/gen0
 8 power                        0   6 wait: send to gimlet_seq/gen0
 9 hiffy                        0   5 notif: bit31(T+61)
10 gimlet_seq                   0   4 (DEAD)
11 gimlet_inspector             0   6 notif: socket
12 hash_driver                  0   2 recv
13 hf                           0   3 recv
14 update_server                0   3 recv
15 sensor                       0   4 recv
16 host_sp_comms                0   7 wait: send to gimlet_seq/gen0
17 udpecho                      0   6 notif: socket
18 udpbroadcast                 0   6 notif: bit31(T+322)
19 control_plane_agent          0   6 recv, notif: usart-irq(irq37) socket timer
20 sprot                        0   4 recv
21 validate                     0   5 recv
22 vpd                          0   4 recv
23 user_leds                    0   2 recv, notif: timer
24 dump_agent                   0   6 recv, notif: socket
25 sbrmi                        0   4 recv
26 idle                         0   8 RUNNING
27 udprpc                       0   6 notif: socket
```

Why is `gimlet_seq` dead? Because its I2C retries have all failed:

```
$ humility -d ./hubris.core.dead-gimlet ringbuf gimlet_seq
humility: ring buffer drv_gimlet_seq_server::__RINGBUF in gimlet_seq:
   TOTAL VARIANT
     446 ClockConfigWrite
       3 I2cFault(BusReset)
       1 I2cFault(BusLocked)
       1 IdentValid(false)
       1 ChecksumValid(false)
       1 Reprogram(true)
       1 Programmed
       1 Programming
       1 Ice40PowerGoodV1P2(true)
       1 Ice40PowerGoodV3P3(true)
       1 RailsOff
       1 Ident
       1 A2Status
       1 A2
       1 StartFailed(I2cFault)
       1 V3P3SysA0VOut
       1 ClockConfigSuccess
       1 Ice40Rails
 NDX LINE      GEN    COUNT PAYLOAD
   0  245        1        1 Ice40Rails(true, true)
   1  274        1        1 Ice40PowerGoodV1P2(true)
   2  295        1        1 Ice40PowerGoodV3P3(true)
   3  337        1        1 IdentValid(false)
   4  340        1        1 ChecksumValid(false)
   5  343        1        1 Reprogram(true)
   6  357        1        1 Programming
   7  386        1        1 Programmed
   8  390        1        1 RailsOff
   9  393        1        1 Ident(0xde01)
  10  399        1        1 A2Status(0x0)
  11  422        1      446 ClockConfigWrite
  12  433        1        1 ClockConfigSuccess
  13 1344        1        1 V3P3SysA0VOut(Volts(0.080078125))
  14  435        1        1 A2
  15  607        1        1 I2cFault { retries_remaining: 0x3, code: BusLocked }
  16  607        1        1 I2cFault { retries_remaining: 0x2, code: BusReset }
  17  607        1        1 I2cFault { retries_remaining: 0x1, code: BusReset }
  18  607        1        1 I2cFault { retries_remaining: 0x0, code: BusReset }
  19  144        1        1 StartFailed(I2cFault)
```

The output doesn't not do a terrific job of indicating what has failed here,
but we have failed to load SPD data.

The `i2c_driver` is reporting that we just... timed out:

```
$ humility -d ./hubris.core.dead-gimlet ringbuf i2c_driver
...
  10  773      250        1 Read(ISR, 0x8025)
  11  773      250        2 Read(ISR, 0x8021)
  12  773      250        1 Read(ISR, 0x8025)
  13  773      250        2 Read(ISR, 0x8021)
  14  773      250        1 Read(ISR, 0x8025)
  15  773      250        2 Read(ISR, 0x8021)
  16  773      250        1 Read(ISR, 0x8025)
  17  773      250        2 Read(ISR, 0x8021)
  18  773      250        1 Read(ISR, 0x9025)
  19  468      250        1 Reset(CR1, 0x1000d6)
  20  477      250        1 Reset(CR2, 0xff04aa)
```

This is reproducible (but only on cold power on!); putting the logic analyzer on, it looks as if the device just decided to clock stretch us:

2024-04-08-12-08-27_1741x336

Zooming out:

2024-04-08-12-11-09_1754x515

We timed out (25ms) and then -- some 31ms later, we see a few wiggles on SCL as we reset the I2C controller from the sequencer. Interestingly, if we continue to wiggle SCL, the bus will become released:

```
$ while true; do humility i2c -b mid -d 0x58 -R ; done
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(BusReset)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Err(NoDevice)
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Success
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Success
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Success
humility: attached via ST-Link V3
Controller I2C3, device 0x58, raw read = Success
^C
```

So... what is going on here?  Well, many things -- but it turns out that it starts with another interesting artifact in the tasks listing.  It's easy to look at `gimlet_seq` because... it's `(DEAD)` and it's the reason that we're not in A2.  But note that the `net` task has also died!  It has left a dump; from [the extracted dump of the net task](https://github.com/oxidecomputer/hubris/files/14910733/hubris.core.net.dead-gimlet.gz)

```
$ humility -d ./hubris.core.net.dead-gimlet tasks
humility: attached to dump
system time = 1132
ID TASK                       GEN PRI STATE    
 1 net                          0   5 FAULT: stack overflow; sp=0x2400ffb0 (was: ready)
```

```
$ humility -d ./hubris.core.net.dead-gimlet readmem -s 0x24010000 512
humility: attached to dump
0x24010000 | 0xbaddcafe
0x24010004 | 0xbaddcafe
0x24010008 | 0xbaddcafe
0x2401000c | 0xbaddcafe
0x24010010 | 0x0807da00
0x24010014 | 0x00000000
0x24010018 | 0x24010988
0x2401001c | 0x0807da00
0x24010020 | 0x24010330
0x24010024 | 0x08077641 <- net:drv_stm32h7_eth::Ethernet::smi_timer_wait+0x3d
0x24010028 | 0x0807b2fa <- net:sys_recv_stub+0x14
0x2401002c | 0x41000000
0x24010030 | 0x00000000
0x24010034 | 0x00000000
0x24010038 | 0x00000000
0x2401003c | 0x00000000
0x24010040 | 0x00000012
0x24010044 | 0x24010070
0x24010048 | 0x24010bf0
0x2401004c | 0x00000010
0x24010050 | 0x24010068
0x24010054 | 0x0806e8b1 <- net:vsc85xx::Phy<P>::set_page+0x35
0x24010058 | 0x24010330
0x2401005c | 0x240100d0
0x24010060 | 0x240100d0
0x24010064 | 0x24010bf0
0x24010068 | 0x240100a8
0x2401006c | 0x0806e843 <- net:vsc85xx::Phy<P>::write_inner+0x17
0x24010070 | 0x240100d0
0x24010074 | 0x24010bf0
0x24010078 | 0x00000010
0x2401007c | 0x00000012
0x24010080 | 0x24010bf0
0x24010084 | 0x240100d0
0x24010088 | 0x24010bf0
0x2401008c | 0x240100a8
0x24010090 | 0x0000800f
0x24010094 | 0x240101a8
0x24010098 | 0x24010330
0x2401009c | 0x24010bf0
0x240100a0 | 0x240100d0
0x240100a4 | 0x24010bf0
0x240100a8 | 0x240100f8
0x240100ac | 0x0806eeed <- net:vsc85xx::util::<impl vsc85xx::Phy<P>>::cmd+0x1f
0x240100b0 | 0x0000800f
0x240100b4 | 0x00000000
0x240100b8 | 0x00000000
0x240100bc | 0x00000000
0x240100c0 | 0x00000000
0x240100c4 | 0x00000000
0x240100c8 | 0x24010988
0x240100cc | 0x0807da00
0x240100d0 | 0x8000ffff
0x240100d4 | 0x24010110
0x240100d8 | 0x240100ec
0x240100dc | 0x24010130
0x240100e0 | 0x0000c018
0x240100e4 | 0x0000fb48
0x240100e8 | 0x24010330
0x240100ec | 0x24010bf0
0x240100f0 | 0x24010bf0
0x240100f4 | 0x240101a8
0x240100f8 | 0x240101d8
0x240100fc | 0x0806ec9d <- net:vsc85xx::util::<impl vsc85xx::Phy<P>>::micro_assert_reset+0x1f
0x24010100 | 0x00000019
0x24010104 | 0x24010988
0x24010108 | 0x00000019
0x2401010c | 0x0000001e
0x24010110 | 0x24010128
0x24010114 | 0x0806d2cb <- net:drv_stm32h7_eth::Ethernet::smi_read+0x47
0x24010118 | 0x00000001
0x2401011c | 0x240101b0
0x24010120 | 0x0000002f
0x24010124 | 0x24010bf0
0x24010128 | 0x24010168
0x2401012c | 0x0806e807 <- net:vsc85xx::Phy<P>::read_inner+0x2b
0x24010130 | 0x2401012f
0x24010134 | 0x24010bf0
0x24010138 | 0x00000001
0x2401013c | 0x00000019
0x24010140 | 0x240101b0
0x24010144 | 0x24010bf0
0x24010148 | 0x0000002f
0x2401014c | 0x24010168
0x24010150 | 0x24010330
0x24010154 | 0x240101b0
0x24010158 | 0x24010330
0x2401015c | 0x0000fb48
0x24010160 | 0x24010bf0
0x24010164 | 0x0000002f
0x24010168 | 0x240101d8
0x2401016c | 0x0806e9bd <- net:vsc85xx::util::<impl vsc85xx::Phy<P>>::read_8051_crc+0x7d
0x24010170 | 0x0000005d
0x24010174 | 0x0000ffff
0x24010178 | 0x00000002
0x2401017c | 0x00000000
0x24010180 | 0x00000000
0x24010184 | 0x00000000
0x24010188 | 0x00000000
0x2401018c | 0x24010330
0x24010190 | 0x0000002f
0x24010194 | 0x24010bf0
0x24010198 | 0x240101d8
0x2401019c | 0x0806e859 <- net:vsc85xx::Phy<P>::write_inner+0x2d
0x240101a0 | 0x2401032f
0x240101a4 | 0x24010bf0
0x240101a8 | 0x00000010
0x240101ac | 0x00000000
0x240101b0 | 0xfb480b2f
0x240101b4 | 0x0000002f
0x240101b8 | 0x24010330
0x240101bc | 0x0000c018
0x240101c0 | 0x0000fb48
0x240101c4 | 0x240103e8
0x240101c8 | 0x00000001
0x240101cc | 0x24010bf0
0x240101d0 | 0x24010330
0x240101d4 | 0x24010330
0x240101d8 | 0x24010358
0x240101dc | 0x0806f3cd <- net:vsc85xx::viper::ViperPhy<P>::patch+0x441
0x240101e0 | 0x0000c018
0x240101e4 | 0xbaddcafe
0x240101e8 | 0xbaddcafe
0x240101ec | 0xbaddcafe
0x240101f0 | 0xbaddcafe
0x240101f4 | 0xbaddcafe
0x240101f8 | 0xbaddcafe
0x240101fc | 0xbaddcafe
```

It all starts to come into focus.

1. Presumably due to the toolchain change, we are now consuming a little more stack space in the `net` task

1. The `net` task dies, and its contents are dumped by `jefe`. This takes ~57ms.

1. This dump -- running at the highest priority of the system -- has the misfortune of occuring in the middle of an i2c transaction.  The controller (correctly) times us out.

1. `i2c_driver` does not wiggle SCL on controller reset (only on controller initialization); resetting the controller induces a single SCL wiggle

1. `gimlet_seq` only retries 3 times, inducing a total of 3 wiggles on SCL -- not nearly enough to clock through a transaction incorrectly, let alone correctly

And as a bonus: `gimlet_seq` has the wrong retry logic with respect to SPD errors anyway:  if it were able to accidentally clock through it (by, say, increasing the retry count to 30), the resulting SPD data would be corrupt.

These problems need to be fixed, but the fixes are fortunately straightforward:

1. The stack size for the `net` task needs to be bumped

1. `i2c_driver` needs to do its existing SCL wiggle dance on a controller reset. This will have the added (positive) side effect of clocking through certain kinds of device misbehavior more explicitly.

1. The SPD retry logic in `gimlet_seq` needs to be fixed

Finally, because it would have been helpful to debug this a little faster, I want to add slightly more `ringbuf` instrumentation to the dump code (record the time!) and to `gimlet_seq` (record the I2C operation that we're attempting).

### PR DESCRIPTION
**Pull request by bcantrill**
Fixes #1741.

### CODE REVIEW

File: drv/gimlet-seq-server/src/main.rs [hunk 1]
```diff
@@ -111,11 +121,16 @@ enum Trace {
     SpdBankAbsent(u8),
     SpdAbsent(u8, u8, u8),
     SpdDimmsFound(usize),
-    I2cFault {
-        retries_remaining: u8,
+    I2cError {
+        txn: I2cTxn,
```
Comment (hawkw) [inline drv/gimlet-seq-server/src/main.rs:125]: One deficiency of the counters crate is that we cannot currently place `#[count(children)]` on multiple fields to generate counts of each unique pair of that field, it would be nice to do that so that we can count the number of errors by transaction type. I might hack that together and we can come back and add it here.

File: drv/gimlet-seq-server/src/main.rs [hunk 2]
```diff
@@ -111,11 +121,16 @@ enum Trace {
...
         #[count(children)]
         code: i2c::ResponseCode,
     },
+    I2cFault(I2cTxn),
+    I2cRetry {
+        txn: I2cTxn,
```
Comment (hawkw) [inline drv/gimlet-seq-server/src/main.rs:131]: Maybe worth adding 
```suggestion
       #[count(children)]
        txn: I2cTxn,
```
here though, so that we can see the breakdown of retries by transaction that was retried?

N.B. that counting variants of the `I2cFault` doesn't seem necessary since it's fatal and we only record one of them, and it will almost certainly still be in the ringbuf if we ever record it...

File: drv/stm32xx-i2c-server/src/main.rs [hunk 3]
```diff
@@ -296,6 +296,44 @@ fn reset_if_needed(
...
+
+            for gpio_pin in &[pin.scl, pin.sda] {
+                sys.gpio_configure_alternate(
+                    *gpio_pin,
+                    OutputType::OpenDrain,
+                    Speed::Low,
+                    Pull::None,
+                    pin.function,
+                );
+            }
```
Comment (hawkw) [inline drv/stm32xx-i2c-server/src/main.rs:330]: This is necessary because `wiggle_scl` puts the SCL pin in GPIO output mode, right? It _might_ be nice if there was a comment --- I was a bit surprised that `wiggle_scl` doesn't just put the pin back the way it found it when it's done, but I see that this is because it previously only happened during initial configuration and the pin AF configuration happens in a separate step.

**Review by hawkw — APPROVED** [review]

File: app/sidecar/base.toml [hunk 4]
```diff
@@ -78,7 +78,7 @@ task-slots = ["sys"]
 
 [tasks.net]
 name = "task-net"
-stacksize = 6040
+stacksize = 8000
```
Comment (mkeeter) [inline app/sidecar/base.toml:81]: Can you bump the stack size in `app/demo-stm32h7-nucleo/app-h753.toml` and `app/demo-stm32h7-nucleo/app-h743.toml` as well?

File: drv/gimlet-seq-server/src/main.rs [hunk 5]
```diff
@@ -1119,7 +1138,20 @@ fn read_spd_data_and_load_packrat(
...
+                    //
+                    // If our read needs to be retried, we need to also reset
+                    // ourselves back to the 0th byte.
+                    //
+                    _ = spd.read_reg::<u8, u8>(0)?;
+                }
+
+                retried = true;
+                spd.read_into(&mut tmp[1..])
+            })?;
```
Comment (mkeeter) [inline drv/gimlet-seq-server/src/main.rs:1154]: It's cleaner to unconditionally read the entire register if the byte-0 read succeeds:
```rust
            // Try reading the first byte; if this fails, we will assume
            // the device isn't present.
            if spd.read_reg::<u8, u8>(0).is_ok() {
                present[usize::from(ndx)] = true;
                npresent += 1;

                // Now do the full read (re-reading byte 0 for simplicity)
                retry_i2c_txn(I2cTxn::SpdLoad(nbank, i), || {
                    spd.read_reg_into(0, &mut tmp)
                })?;

                packrat.set_spd_eeprom(ndx, false, 0, &tmp);
            } else {
                ringbuf_entry!(Trace::SpdAbsent(nbank, i, ndx));
            }
```
(and I don't think it's worth the extra complexity to avoid re-reading byte 0)

File: drv/gimlet-seq-server/src/main.rs [hunk 6]
```diff
@@ -1146,9 +1178,16 @@ fn read_spd_data_and_load_packrat(
...
 
-            retry_i2c_txn(|| spd.read_into(&mut tmp[chunk..]))?;
+            retry_i2c_txn(I2cTxn::SpdLoadTop(nbank, i), || {
+                //
+                // Both of these reads need to be in a single transaction from
+                // the perspective of the retry logic: if either fails, we
+                // must redo both.
+                //
+                spd.read_reg_into::<u8>(0, &mut tmp[..chunk])?;
+                spd.read_into(&mut tmp[chunk..])
```
Comment (mkeeter) [inline drv/gimlet-seq-server/src/main.rs:1189]: Dumb question: why do these reads need to be separate, versus
```suggestion
                spd.read_reg_into::<u8>(0, &mut tmp)?;
```

File: drv/gimlet-seq-server/src/main.rs [hunk 7]
```diff
@@ -1302,8 +1341,8 @@ cfg_if::cfg_if! {
             let (device, rail) = i2c_config::pmbus::vddcr_soc(i2c);
             let mut vddcr_soc = Raa229618::new(&device, rail);
 
-            retry_i2c_txn(|| vdd_vcore.turn_off())?;
-            retry_i2c_txn(|| vddcr_soc.turn_off())?;
+            retry_i2c_txn(I2cTxn::VCoreOff, || vdd_vcore.turn_off())?;
```
Comment (mkeeter) [inline drv/gimlet-seq-server/src/main.rs:1344]: Is there any reason to believe these two commands should be in a transaction together?  (same for `VCoreOn` / `SocOn` below)

File: drv/gimlet-seq-server/src/main.rs (hunk 5 above)
Comment (bcantrill) [reply drv/gimlet-seq-server/src/main.rs:1154]: There's a limit of 255 bytes on an i2c read, so this needs to be over two reads anyway, FWIW.

File: drv/gimlet-seq-server/src/main.rs (hunk 6 above)
Comment (bcantrill) [reply drv/gimlet-seq-server/src/main.rs:1189]: Same reply here: the 255 byte limit on i2c operations.

File: drv/gimlet-seq-server/src/main.rs (hunk 7 above)
Comment (bcantrill) [reply drv/gimlet-seq-server/src/main.rs:1344]: No, these don't need to be grouped together.

File: drv/gimlet-seq-server/src/main.rs (hunk 2 above)
Comment (bcantrill) [reply drv/gimlet-seq-server/src/main.rs:132]: Good idea; fixed.
