### PR TITLE
cpu_seq: Fix a variety of hilarious bugs in sequencer IRQ handling

### LINKED ISSUE #2384: On Cosmo, hubris misses NIC_MAPO leading to a fake "Overheat"
Here's a snip from the cosmo_seq that shows the issue, I've included from the inital power on just to set the baseline.

```
   TOTAL VARIANT
   13942 RegStateValues
     534 ContinueBitstreamLoad
     112 CPUPresent
       3 SetState(InitialPowerOn)
       1 SetState(Overheat)
       1 FpgaInit
       1 WaitForDone
       1 Programmed
       1 Startup
       1 SequencerInterrupt
       1 Coretype
       1 PmbusAlert
 NDX LINE      GEN    COUNT PAYLOAD
...
 62  468        6        1 SetState { prev: Some(A0), next: A0PlusHP, why: InitialPowerOn, now: 0x231fa }
  63  442        6       97 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: 0xe }, nic_api_status: NicApiStatusView { nic_sm: Ok(Done) }, nic_raw_status: NicRawStatusView { hw_sm: 0x6 } }
  64  442        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: 0xe }, nic_api_status: NicApiStatusView { nic_sm: Ok(NicReset) }, nic_raw_status: NicRawStatusView { hw_sm: 0x6 } }
  65  442        6      171 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: 0xe }, nic_api_status: NicApiStatusView { nic_sm: Ok(Done) }, nic_raw_status: NicRawStatusView { hw_sm: 0x6 } }
  66  741        6        1 SequencerInterrupt { our_state: A0PlusHP, seq_state: Ok(Done), ifr: IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: false, amd_pwrok_fedge: false, amd_rstn_fedge: false, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: false, vr_v3p3_sys_to_fpga1_alert: false, vr_v5p0_sys_to_fpga1_alert: false, v0p96_nic_to_fpga1_alert: false, pwr_cont1_to_fpga1_alert: true, pwr_cont2_to_fpga1_alert: false, pwr_cont3_to_fpga1_alert: false } }
  67  781        6        1 PmbusAlert { now: 0x64b4d }
  68  442        6       56 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: 0xe }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: 0x0 } }
  69  468        6        1 SetState { prev: Some(A0PlusHP), next: A2, why: Overheat, now: 0x72435 }
  70  442        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Disabling) }, seq_raw_status: SeqRawStatusView { hw_sm: 0xf }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: 0x0 } }
  71  442        6        2 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Idle) }, seq_raw_status: SeqRawStatusView { hw_sm: 0x0 }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: 0x0 } }
```
The sequence goes like this:

1. At NDX 64, we're up and happy, in A0HP, the nic domain is up.
2. The 12V rail droops due to a BMR491 dropout (mitigated in newer code than was running on this target).
3. The 12V rail droop causes some pmbus alerts, and we expect the T6's MAX5970 to UVLO, the pmbus alert is seen in NDX 66/67.
4. At NDX 68, it is clear that the FPGA has MAPO'd the nic domain as we're back in IDLE.  I expect this should have set the nic mapo IFR, but we don't see indication of that in this trace.  See https://github.com/oxidecomputer/quartz/blob/11f53ccfd9bcab5d823a8f4f51bd3b183481b999/hdl/projects/cosmo_seq/sequencer/sims/sp5_seq_sim_tb.vhd#L77 and https://github.com/oxidecomputer/quartz/blob/11f53ccfd9bcab5d823a8f4f51bd3b183481b999/hdl/projects/cosmo_seq/sequencer/sims/sp5_seq_sim_pkg.vhd#L176 for FPGA sims confirming this functionality at the FPGA.
5. NIC domain MAPO prevents us from talking to the T6 temp sensor. This is interlocked in hardware so that we can't i2c to an un-powered device. The result here is that any attempted read will be a NACK.
6. We're in this state long enough to have 56 logs, but since hubris thinks we're still in A0HP we continue polling the T6 temp sensor for temp. @sdonnan points out that this [code](https://github.com/oxidecomputer/hubris/blob/ddfb8782336a86cf5c04e48eedc05d6a0ee25756/task/thermal/src/control.rs#L507) artificially increases the temperature a little bit each missing read.
7. Finally, we sit here long enough that the fake T6 temperature exceeds the limit and we move to A2 due to an "Overheat" although in this case, it's totally fake.

### LINKED ISSUE #2389: RAA229620A (and perhaps also RAA229618?) input undervolt faults never actually get cleared
This was missed because our code for the sequencer interrupt is edge triggered, and the VRMs appear to just never de-assert their PMBus alert pin once they see a Vin warning. Because the EXTI IRQ fires on the falling edge we would just miss any subsequent IRQs after the line has been asserted once , since it never goes low again until the VRMs are totally reset. On Cosmo, this means _any_ subsequent sequencer FPGA alert is also missed.

### PR DESCRIPTION
**Pull request by hawkw**
Depends on #2392 

There are several things wrong with the current handling of sequencer FPGA interrupts (on Cosmo) and PMBus alerts in the Gimlet sequencer. To wit: 

1. On Cosmo, the `cosmo_seq_server` task does not handle the `NIC_MAPO` interrupt from the sequencer FPGA. When the NIC MAPOs, we should be transitioning from A0+HP back to A0, rather than just ignoring the NIC MAPO event. Presently, ignoring NIC MAPOs result in an improper thermal shutdown (see #2384), as the `thermal` task continues to poll the NIC's temperature sensor despite it no longer being powered, and extrapolates a worst-case temperature trend in the face of I2C NACKs from the temperature sensor, which eventually result in a thermal shutdown. This isn't great.
2. Both the Cosmo sequencer FPGA interrupt and the Gimlet V<sub>core</sub> VRM PMBus alert handling are implemented using the STM32 external interrupt (EXTI) peripheral, which only supports edge-triggered interrupts (not level-triggered). On Cosmo, where the FPGA IRQ line can be triggered by multiple bits in the FPGA's Interrupt Flags Register (IFR)  being set, this means that we can miss interrupts in a situation where one IFR bit is set and then, *after* Hubris reads the IFR, a second IFR bit is *also* set while the `FPGA1_TO_SP_IRQ_L` line remains asserted. In this case, any bits which are set after the initial IFR read are completely missed by Hubris.

   Sadly, it turns out that this is often what happens in the event of a voltage sag on `V12_SYS_A2` similar to mfg-quality#140. If the voltage dips enough to both trigger the RAA229620A's V<sub>in</sub> undervolt warning **and** enough to MAPO the T6, the T6 MAPO tends to occur while we are in the interrupt handler but after the initial IFR read, so the NIC MAPO interrupt tends to be missed. Cool.
3. Our code that attempts to clear PMBus faults in the RAA229620As (on Cosmo)/RAA229618 (on Gimlet)...doesn't due that (see #2389), due to multiple _hilarious_ bugs:
    - We are currently sending the PMBus `CLEAR_FAULTS` command without a PMBus page (rail) associated with it. It turns out that this does _not_ actually result in clearing faults on all pages. Instead, it results in, uh, nothing happening.
      
      Quoth the PMBus standard:
      > Commands to clear a bit are gated by the PAGE command. The CLEAR_FAULTS can
      > be made to clear all faults on all pages by setting the page command to FFh.
      >
      > --- _PMBus Power System Mgt Protocol Specification – Part II – Revision 1.3.1_; §10.3 (p. 44)
    
      So, sending the command without a page doesn't actually do anything. That's great.
    - The second thing that stops this from working is _technically_ our fault but is due to a decision on the part of the vendor which is both profoundly bone-headed and somewhat poorly documented (as is traditional). As @nathanaelhuffman discovered,  the RAA229620A documentation for the `VIN_UV_FAULT_RESPONSE` register, states the following:

         > Configures the input undervoltage fault response. **For a fault to be considered cleared, the input
         > voltage must rise by 1/16th of the UV fault threshold value.** 
         > --- _R16DS0309EU0100 Rev.1.00_ §11.36 "VIN_OV_FAULT_RESPONSE"  (p. 57) (emphasis mine)

         When we configure the undervoltage warning, [we set the threshold to 11.75V][1]. If you remember fractions from...elementary school?[^1] you may have already realized that 1/16 * 11.75V = 0.734375V. This means that for the VRM to clear the fault, the input voltage must reach 12.484375V (since 11.75V + 0.734375V = 12.484375V). 

         Yes, that is *almost half a volt above the nominal voltage for the 12V rail*. It isn't supposed to do that! It's supposed to be 12V!! So, even if a voltage sag has ended and the input voltage to the VRM has returned to 12V, the fault will not clear because the voltage has not increased by the requisite 1/16th of the undervolt threshold. Isn't that wonderful?
5. There was also a FPGA bug in which the `NIC_MAPO` bit did not actually get unset as expected.

This branch unwinds the entire Litany of Sadness and Pain described above, by doing the following things:

- Integrating with @nathanaelhuffman's changes in oxidecomputer/quartz#467, which fixes the bug with clearing the `IFR[NIC_MAPO]` bit, and also changes all the IFR flags to be write-1-to-clear. Now, we can clear them properly in the Cosmo sequencer's routine for handling FPGA IRQs. This required #2392 as the new FPGA register map wouldn't build without it.
- Actually making the NIC MAPO interrupt transition the system state from A0+HP to A0, which (in conjunction with #2391) fixes #2384.
- Changing the code for clearing RAA22960A and RAA229618 PMBus faults to do paged writes rather than unpaged writes, fixing #2389.
- Changing the V<sub>in</sub> undervolt warning threshold from 11.75V to 11V, so that the fault actually clears when the input voltage returns to normal.
- On Cosmo, changing the code for handling the EXTI notification to continue reading the FPGA IFR register and clearing any set interrupt bits until the IRQ line is actually deasserted in a loop, to compensate for the possibility of additional bits being set whilst we are already handling an interrupt but after we have read the IFR. 

  This does not apply to the PMBus alerts from the RAA229620As, as they are set in the IFR as long as the corresponding PMBus alert line to the FPGA is asserted, and cannot be cleared by writing back a 1 to the IFR. Instead, we mask them out by setting the corresponding bits in the FPGA Interrupt Enable Register (IER), so that they can remain asserted without the FPGA continuing to assert the IRQ. 
- Masking out the RAA229620A PMBus alerts _half-solves_ the problem, but it doesn't reset the IER when the PMBus fault actually does clear, so we wouldn't be notified of a _subsequent_ fault condition. Thus, we must also set a flag that tells the sequencer task to continue trying to clear faults in the VRM(s) that asserted the PMBus alert periodically until the fault actually goes away. If it does, we then re-enable IRQs for the corresponding `PMALERT_L` pin(s).
- A slightly simpler version of that also had to happen on Gimlet. It's simpler because Gimlet only monitors a single RAA229618.

Whew okay yeah, I think that's everything. This was a whole thing.

Fixes #2384
Fixes #2389

[1]: https://github.com/oxidecomputer/hubris/blob/939c48a1ff8e3ab059d8813f6a58b82fdaccc562/drv/cosmo-seq-server/src/vcore.rs#L85-L91
[^1]: Or middle school? When do children learn fractions?

### CODE REVIEW

**Comment by hawkw** [comment]
_whew_ okay i think i this Cosmo just did _everything i wanted it to do and nothing i didn't want it to do_!

```console
eliza@alfred ~ $ pfexec humility pmbus -r V12_SYS_A2 -w VOUT_COMMAND=8 \
  && pfexec humility pmbus -r V12_SYS_A2 -w VOUT_COMMAND=12 \
  && pfexec humility ringbuf cosmo_seq \
  && pfexec humility pmbus -s
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
humility: I2C4, port F, dev 0x67: successfully wrote VOUT_COMMAND
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
humility: I2C4, port F, dev 0x67: successfully wrote VOUT_COMMAND
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
humility: ring buffer drv_cosmo_seq_server::__RINGBUF in cosmo_seq:
   TOTAL VARIANT
   14105 RegStateValues
     534 ContinueBitstreamLoad
     112 CPUPresent
       3 SetState(InitialPowerOn)
       2 PmbusAlert
       2 EreportSent
       1 FpgaInit
       1 WaitForDone
       1 Programmed
       1 Startup
       1 SequencerInterrupt
       1 Coretype
       1 ResetCounts
       1 NicMapoInterrupt
 NDX LINE      GEN    COUNT PAYLOAD
  76  601        5        1 CPUPresent(true)
  77  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  78  601        5        1 CPUPresent(true)
  79  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  80  601        5        1 CPUPresent(true)
  81  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  82  601        5        1 CPUPresent(true)
  83  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  84  601        5        1 CPUPresent(true)
  85  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  86  601        5        1 CPUPresent(true)
  87  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  88  601        5        1 CPUPresent(true)
  89  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  90  601        5        1 CPUPresent(true)
  91  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  92  601        5        1 CPUPresent(true)
  93  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  94  601        5        1 CPUPresent(true)
  95  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  96  601        5        1 CPUPresent(true)
  97  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  98  601        5        1 CPUPresent(true)
  99  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 100  601        5        1 CPUPresent(true)
 101  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 102  601        5        1 CPUPresent(true)
 103  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 104  601        5        1 CPUPresent(true)
 105  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 106  601        5        1 CPUPresent(true)
 107  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 108  601        5        1 CPUPresent(true)
 109  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 110  601        5        1 CPUPresent(true)
 111  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 112  601        5        1 CPUPresent(true)
 113  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 114  601        5        1 CPUPresent(true)
 115  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 116  601        5        1 CPUPresent(true)
 117  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 118  601        5        1 CPUPresent(true)
 119  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 120  601        5        1 CPUPresent(true)
 121  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 122  601        5        1 CPUPresent(true)
 123  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 124  601        5        1 CPUPresent(true)
 125  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
 126  601        5        1 CPUPresent(true)
 127  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
   0  601        6        1 CPUPresent(true)
   1  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
   2  601        6        1 CPUPresent(true)
   3  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
   4  601        6        1 CPUPresent(true)
   5  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
   6  601        6        1 CPUPresent(true)
   7  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
   8  601        6        1 CPUPresent(true)
   9  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  10  601        6        1 CPUPresent(true)
  11  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  12  601        6        1 CPUPresent(true)
  13  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  14  601        6        1 CPUPresent(true)
  15  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  16  601        6        1 CPUPresent(true)
  17  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  18  601        6        1 CPUPresent(true)
  19  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  20  601        6        1 CPUPresent(true)
  21  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  22  601        6        1 CPUPresent(true)
  23  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  24  601        6        1 CPUPresent(true)
  25  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  26  601        6        1 CPUPresent(true)
  27  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  28  601        6        1 CPUPresent(true)
  29  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  30  601        6        1 CPUPresent(true)
  31  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  32  601        6        1 CPUPresent(true)
  33  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  34  601        6        1 CPUPresent(true)
  35  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  36  601        6        1 CPUPresent(true)
  37  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  38  601        6        1 CPUPresent(true)
  39  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  40  601        6        1 CPUPresent(true)
  41  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  42  601        6        1 CPUPresent(true)
  43  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  44  601        6        1 CPUPresent(true)
  45  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  46  601        6        1 CPUPresent(true)
  47  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  48  601        6        1 CPUPresent(true)
  49  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  50  601        6        1 CPUPresent(true)
  51  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  52  601        6        1 CPUPresent(true)
  53  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  54  601        6        1 CPUPresent(true)
  55  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  56  601        6        1 CPUPresent(true)
  57  530        6        2 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Sp5FinalCheckpoint) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(WaitPwrok) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  58  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(EnablePower) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(WaitForPgs) } }
  59  632        6        1 Coretype { coretype0: true, coretype1: false, coretype2: true, sp5r1: true, sp5r2: false, sp5r3: false, sp5r4: false }
  60  530        6    13232 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(NicReset) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
  61  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Done) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
  62  556        6        1 SetState { prev: Some(A0), next: A0PlusHP, why: InitialPowerOn, now: 0x2272b }
  63  530        6       88 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Done) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
  64  530        6        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(NicReset) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
  65  530        6        2 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Done) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
  66 1059        6        1 SequencerInterrupt { our_state: A0PlusHP, seq_state: Ok(Done) }
  67  830        6        1 SequencerIfr(IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: false, amd_pwrok_fedge: false, amd_rstn_fedge: false, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: true, vr_v3p3_sys_to_fpga1_alert: true, vr_v5p0_sys_to_fpga1_alert: true, v0p96_nic_to_fpga1_alert: true, pwr_cont1_to_fpga1_alert: true, pwr_cont2_to_fpga1_alert: false, pwr_cont3_to_fpga1_alert: false })
  68  878        6        1 PmbusAlert { now: 0x38a11 }
  69 1134        6        1 EreportSent(0x87)
  70 1134        6        1 EreportSent(0x88)
  71  830        6        1 SequencerIfr(IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: true, amd_pwrok_fedge: false, amd_rstn_fedge: true, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: true, vr_v3p3_sys_to_fpga1_alert: true, vr_v5p0_sys_to_fpga1_alert: true, v0p96_nic_to_fpga1_alert: true, pwr_cont1_to_fpga1_alert: true, pwr_cont2_to_fpga1_alert: true, pwr_cont3_to_fpga1_alert: false })
  72  878        6        1 PmbusAlert { now: 0x38a47 }
  73  910        6        1 ResetCounts { rstn: 0x1, pwrokn: 0x0 }
  74  916        6        1 NicMapoInterrupt
  75  530        6      666 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
humility: ring buffer drv_cosmo_seq_server::vcore::__RINGBUF in cosmo_seq:
 NDX LINE      GEN    COUNT PAYLOAD
   0  150        1        1 Initializing
   1  159        1        1 LimitsLoaded
   2  205        1        1 StatusWords { vddcr_cpu0: Ok(0x0), vddcr_cpu1: Ok(0x0) }
   3  170        1        1 Initialized
   4  220        1        1 PmbusAlert { timestamp: 0x38a11, vrms: Vrms { pwr_cont1: true, pwr_cont2: false } }
   5  330        1        1 StatusWord(VddcrCpu0, Ok(0x2001))
   6  370        1        1 RegulatorStatus { rail: VddcrCpu0, power_good: true, faulted: true }
   7  393        1        1 StatusInput(VddcrCpu0, Ok(0x20))
   8  405        1        1 StatusVout(VddcrCpu0, Ok(0x0))
   9  409        1        1 StatusIout(VddcrCpu0, Ok(0x0))
  10  414        1        1 StatusTemperature(VddcrCpu0, Ok(0x0))
  11  418        1        1 StatusCml(VddcrCpu0, Ok(0x0))
  12  423        1        1 StatusMfrSpecific(VddcrCpu0, Ok(0x0))
  13  330        1        1 StatusWord(VddcrCpu1, Ok(0x2001))
  14  370        1        1 RegulatorStatus { rail: VddcrCpu1, power_good: true, faulted: true }
  15  393        1        1 StatusInput(VddcrCpu1, Ok(0x20))
  16  405        1        1 StatusVout(VddcrCpu1, Ok(0x0))
  17  409        1        1 StatusIout(VddcrCpu1, Ok(0x0))
  18  414        1        1 StatusTemperature(VddcrCpu1, Ok(0x0))
  19  418        1        1 StatusCml(VddcrCpu1, Ok(0x0))
  20  423        1        1 StatusMfrSpecific(VddcrCpu1, Ok(0x0))
  21  285        1        1 Reading { timestamp: 0x38a1d, vddcr_cpu0_vin: Volts(9.97), vddcr_cpu1_vin: Volts(9.960001) }
  22  285        1        1 Reading { timestamp: 0x38a1e, vddcr_cpu0_vin: Volts(9.830001), vddcr_cpu1_vin: Volts(9.81) }
  23  285        1        1 Reading { timestamp: 0x38a20, vddcr_cpu0_vin: Volts(9.670001), vddcr_cpu1_vin: Volts(9.650001) }
  24  285        1        1 Reading { timestamp: 0x38a22, vddcr_cpu0_vin: Volts(9.540001), vddcr_cpu1_vin: Volts(9.490001) }
  25  285        1        1 Reading { timestamp: 0x38a23, vddcr_cpu0_vin: Volts(9.39), vddcr_cpu1_vin: Volts(9.340001) }
  26  285        1        1 Reading { timestamp: 0x38a25, vddcr_cpu0_vin: Volts(9.22), vddcr_cpu1_vin: Volts(9.190001) }
  27  285        1        1 Reading { timestamp: 0x38a27, vddcr_cpu0_vin: Volts(9.080001), vddcr_cpu1_vin: Volts(9.030001) }
  28  285        1        1 Reading { timestamp: 0x38a28, vddcr_cpu0_vin: Volts(8.920001), vddcr_cpu1_vin: Volts(8.900001) }
  29  285        1        1 Reading { timestamp: 0x38a2a, vddcr_cpu0_vin: Volts(8.790001), vddcr_cpu1_vin: Volts(8.740001) }
  30  285        1        1 Reading { timestamp: 0x38a2c, vddcr_cpu0_vin: Volts(8.630001), vddcr_cpu1_vin: Volts(8.6) }
  31  285        1        1 Reading { timestamp: 0x38a2d, vddcr_cpu0_vin: Volts(8.4800005), vddcr_cpu1_vin: Volts(8.450001) }
  32  285        1        1 Reading { timestamp: 0x38a2f, vddcr_cpu0_vin: Volts(8.320001), vddcr_cpu1_vin: Volts(8.290001) }
  33  285        1        1 Reading { timestamp: 0x38a30, vddcr_cpu0_vin: Volts(8.160001), vddcr_cpu1_vin: Volts(8.13) }
  34  285        1        1 Reading { timestamp: 0x38a32, vddcr_cpu0_vin: Volts(8.040001), vddcr_cpu1_vin: Volts(8.02) }
  35  285        1        1 Reading { timestamp: 0x38a34, vddcr_cpu0_vin: Volts(7.9900007), vddcr_cpu1_vin: Volts(8.01) }
  36  285        1        1 Reading { timestamp: 0x38a35, vddcr_cpu0_vin: Volts(8.000001), vddcr_cpu1_vin: Volts(8.01) }
  37  285        1        1 Reading { timestamp: 0x38a37, vddcr_cpu0_vin: Volts(7.9900007), vddcr_cpu1_vin: Volts(8.01) }
  38  285        1        1 Reading { timestamp: 0x38a39, vddcr_cpu0_vin: Volts(7.9900007), vddcr_cpu1_vin: Volts(8.000001) }
  39  285        1        1 Reading { timestamp: 0x38a3a, vddcr_cpu0_vin: Volts(7.9900007), vddcr_cpu1_vin: Volts(8.01) }
  40  285        1        1 Reading { timestamp: 0x38a3c, vddcr_cpu0_vin: Volts(7.9900007), vddcr_cpu1_vin: Volts(8.01) }
  41  285        1        1 Reading { timestamp: 0x38a3e, vddcr_cpu0_vin: Volts(7.9800005), vddcr_cpu1_vin: Volts(8.02) }
  42  285        1        1 Reading { timestamp: 0x38a3f, vddcr_cpu0_vin: Volts(7.9800005), vddcr_cpu1_vin: Volts(8.02) }
  43  285        1        1 Reading { timestamp: 0x38a41, vddcr_cpu0_vin: Volts(7.9800005), vddcr_cpu1_vin: Volts(8.02) }
  44  285        1        1 Reading { timestamp: 0x38a43, vddcr_cpu0_vin: Volts(7.9900007), vddcr_cpu1_vin: Volts(8.02) }
  45  285        1        1 Reading { timestamp: 0x38a44, vddcr_cpu0_vin: Volts(7.9800005), vddcr_cpu1_vin: Volts(8.030001) }
  46  205        1        1 StatusWords { vddcr_cpu0: Ok(0x2001), vddcr_cpu1: Ok(0x2001) }
  47  220        1        1 PmbusAlert { timestamp: 0x38a47, vrms: Vrms { pwr_cont1: true, pwr_cont2: true } }
  48  205        1      297 StatusWords { vddcr_cpu0: Ok(0x2001), vddcr_cpu1: Ok(0x2001) }
  49  205        1        1 StatusWords { vddcr_cpu0: Ok(0x2001), vddcr_cpu1: Ok(0x0) }
  50  205        1        1 StatusWords { vddcr_cpu0: Ok(0x0), vddcr_cpu1: Ok(0x0) }
humility: ring buffer drv_i2c_devices::bmr491::__RINGBUF in cosmo_seq:
 NDX LINE      GEN    COUNT PAYLOAD
   0  186        1        1 MitigationApplied(AlreadyApplied)
humility: ring buffer drv_oxide_vpd::__RINGBUF in cosmo_seq:
humility: ring buffer drv_packrat_vpd_loader::__RINGBUF in cosmo_seq:
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
DEVICE      RAIL               PG? #FLT       VIN      VOUT      IOUT    TEMP_1
tps546b24a  V3P3_SP_A2           Y    2   11.984V    3.309V    0.421A  38.000°C
tps546b24a  V5_SYS_A2            Y    2   12.000V    4.986V    1.229A  35.250°C
tps546b24a  V1P8_SYS_A2          Y    2   12.000V    1.795V   -0.453A  31.750°C
raa229620a  VDDCR_CPU0_A0        Y    0   11.970V    0.889V   26.900A  37.000°C
raa229620a  VDDCR_SOC_A0         Y    0   11.980V    0.900V   25.200A  37.000°C
raa229620a  VDDCR_CPU1_A0        Y    0   12.050V    0.890V   25.100A  40.000°C
raa229620a  VDDIO_SP5_A0         Y    0   12.040V    1.100V    1.100A  38.000°C
isl68224    V1P1_SP5_A0          Y    0   11.970V    1.099V    5.700A  34.000°C
isl68224    V1P8_SP5_A1          Y    0   11.960V    1.800V    1.500A  31.000°C
isl68224    V3P3_SP5_A1          Y    0   11.970V    2.750V    0.100A  33.000°C
tps546b24a  V0P96_NIC_VDD_A0HP   N    1    0.000V    0.012V   -0.129A  30.250°C
bmr491      V12_SYS_A2           Y    0   48.000V   11.997V   12.750A  36.750°C
lm5066i     V54P5_FAN_EAST       Y    0   48.178V   48.218V         -  31.125°C
lm5066i     V54P5_FAN_CENTRAL    Y    0   48.092V   48.110V         -  29.250°C
lm5066i     V54P5_FAN_WEST       Y    0   48.070V   48.131V         -  27.188°C
adm127x     V54P5_IBC_A3       --  error: can't read VOUT_MODE: NoRegister  --
eliza@alfred ~ $
```

**Comment by hawkw** [comment]
i regret to inform you that
```console
eliza@alfred ~ $ pfexec humility ringbuf thermal
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
humility: ring buffer drv_i2c_devices::emc2305::__RINGBUF in thermal:
humility: ring buffer drv_i2c_devices::max31790::__RINGBUF in thermal:
humility: ring buffer task_thermal::__RINGBUF in thermal:
   TOTAL VARIANT
    1641 ControlPwm
      99 SensorReadFailed
       3 AutoState(Boot)
       2 AutoState(Running)
       1 AutoState(Critical)
       1 AutoState(Uncontrollable)
       6 FanAdded
       3 MiscReadFailed
       2 PowerModeChanged
       1 Start
       1 ThermalMode(Auto)
       1 PowerDownDueTo
       1 CriticalDueTo
       1 FanControllerInitialized
       1 PowerDownAt
       1 SetFanWatchdogOk
 NDX LINE      GEN    COUNT PAYLOAD
   3 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
   4 1401        7        1 CriticalDueTo { sensor_id: SensorId(0x38), temperature: Celsius(80.326996) }
   5 1409        7        1 AutoState(Critical)
   6 1352        7        1 ControlPwm(0x64)
   7 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
   8 1352        7        1 ControlPwm(0x64)
   9 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  10 1352        7        1 ControlPwm(0x64)
  11 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  12 1352        7        1 ControlPwm(0x64)
  13 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  14 1352        7        1 ControlPwm(0x64)
  15 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  16 1352        7        1 ControlPwm(0x64)
  17 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  18 1352        7        1 ControlPwm(0x64)
  19 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  20 1352        7        1 ControlPwm(0x64)
  21 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  22 1352        7        1 ControlPwm(0x64)
  23 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  24 1352        7        1 ControlPwm(0x64)
  25 1031        7        1 SensorReadFailed(SensorId(0x38), I2cError(NoDevice))
  26 1276        7        1 PowerDownDueTo { sensor_id: SensorId(0x38), temperature: Celsius(85.326996) }
  27 1478        7        1 OverheatedFor(0x2710)
  28 1481        7        1 CriticalFor(0x2710)
  29 1444        7        1 AutoState(Uncontrollable)
  30 1356        7        1 PowerDownAt(0x504a3)
  31 1100        7        1 PowerModeChanged(PowerBitmask(0b1))
   0  924        8        1 AutoState(Boot)
   1 1388        8        1 AutoState(Running)
   2 1352        8     1320 ControlPwm(0x0)
eliza@alfred ~ $
```


...the sequencer task taking us from A0+HP back to A0 (normal) does not make the thermal loop Stop Doing That.

so this fixes, uh, everything _except_ the actual bug (#2384)

**Comment by hawkw** [comment]
@rmustacc informs me that this may actually be Cosmo-only as T6's temperature sensor may be powered in the A0 domain on Gimlet --- if that's the case, we can probably back this out on Gimlet, as it would just add an additional reset of some of the thermal loop parameters for no real reason.

**EDIT**: er, this comment was meant to be left on #2391, which is why it doesn't really make sense here. The Gimlet handling of the RAA229618 PMBus alert is _also_ wrong and the subset of this change that applies to gimlet is indeed valid.

**Comment by hawkw** [comment]
I think that I shall pull the FMC peripheral codegen changes out into its own PR so that that can be reviewed separately.

File: drv/cosmo-seq-server/src/main.rs [hunk 1]
```diff
@@ -736,6 +739,8 @@ impl ServerImpl {
     fn poll_interval(&self) -> Option<u32> {
         match self.state {
             PowerState::A0 => Some(10),
+            // we are hoping that a VRM fault will be clearable soon...
+            _ if self.vcore.is_still_faulted() => Some(100),
```
Comment (labbott) [inline drv/cosmo-seq-server/src/main.rs:753]: oh wow this is new syntax I hadn't seen before!

File: drv/cosmo-seq-server/src/main.rs [hunk 2]
```diff
@@ -893,40 +935,70 @@ impl ServerImpl {
...
             InternalAction::Reset => {
                 // host_sp_comms will be notified of this change and will
                 // call back into this task to reboot the system (going to
                 // A2 then back into A0)
+                ringbuf_entry!(Trace::SetState {
+                    prev: Some(self.state),
+                    next: PowerState::A0Reset,
+                    why: StateChangeReason::CpuReset,
+                    now,
+                });
```
Comment (labbott) [inline drv/cosmo-seq-server/src/main.rs:994]: Will we eventually end up with a redundant ringbuf entry since we should eventually get a call to `set_state` -> `set_state_impl` from `host_sp_comms`?

File: drv/cosmo-seq-server/src/main.rs [hunk 3]
```diff
@@ -1025,7 +1097,17 @@ impl NotificationHandler for ServerImpl {
...
+            ringbuf_entry!(Trace::SequencerInterrupt {
+                our_state: self.state,
+                seq_state: state.seq,
+            });
+
+            // Read the IFR register and handle any pending interrupts until the
+            // SEQ_IRQ signal is deasserted (it's active low).
+            while self.sys.gpio_read(SEQ_IRQ) == 0 {
+                self.handle_sequencer_interrupt();
+            }
```
Comment (labbott) [inline drv/cosmo-seq-server/src/main.rs:1177]: Infinite polling is a little scary. Is there any detection we could add here for something has really gone off the (power) rails or would this be a legit FPGA bug to loop forever?

File: drv/cosmo-seq-server/src/vcore.rs [hunk 4]
```diff
@@ -75,20 +80,89 @@ enum Trace {
...
+            Err(e) => Status::I2cError(e),
+        }
+    }
+
+    fn is_faulted(&self) -> bool {
+        match self {
+            Status::NotFaulted => false,
+            Status::StatusWord(word) => {
+                // Mask out the "off" bit, as "off" is not a fault.
+                //
```
Comment (labbott) [inline drv/cosmo-seq-server/src/vcore.rs:107]: stupid question but when would we observe the "off" bit set?

File: drv/i2c-devices/src/lib.rs [hunk 5]
```diff
@@ -143,6 +143,19 @@ macro_rules! pmbus_write {
 }
 
 macro_rules! pmbus_rail_write {
+    // Write a command with no additional data bytes.
+    ($device:expr, $rail:expr, $cmd:ident) => {{
+        let rpayload = [PAGE::CommandData::code(), $rail];
+        let payload: [u8; 1] = [CommandCode::$cmd as u8];
```
Comment (labbott) [inline drv/i2c-devices/src/lib.rs:149]: Based on below is this supposed to be `$cmd::CommandData::code()`?

Comment (hawkw) [reply drv/i2c-devices/src/lib.rs:149]: Nope, these are actually different! See: https://github.com/oxidecomputer/hubris/blob/556e884f6c4bce4edf6954673a119e9b216b27ed/drv/i2c-devices/src/lib.rs#L112-L137

I believe the `CommandData` type is only generated by the `pmbus` crate codegen when a command has both a command code _and_ associated data. `CLEAR_FAULTS` doesn't, so it's only defined as a variant of the `CommandCode` enum. I had actually originally written this as `$cmd::CommandCode::code()`, but it turns out that doesn't even compile.

File: drv/cosmo-seq-server/src/main.rs (hunk 3 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:1177]: I think it would be a FPGA bug, as we are clearing the bits for each interrupt that's enabled as we see them, which _should_ always result in `SEQ_IRQ` eventually being deasserted unless more and more interrupts are firing. But, I also don't really like the infinite loop. One thing we could do to make this less infinite is change it to loop a fixed number of times, and then if the IRQ line is still asserted, set the timer to a small number and come back and check it again even if the actual notification hasn't been posted to us.

Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:1177]: @labbott perhaps something like this?[^1]
```patch
diff --git a/drv/cosmo-seq-server/src/main.rs b/drv/cosmo-seq-server/src/main.rs
index 108444d8..741023b5 100644
--- a/drv/cosmo-seq-server/src/main.rs
+++ b/drv/cosmo-seq-server/src/main.rs
@@ -739,6 +739,8 @@ impl ServerImpl {
     fn poll_interval(&self) -> Option<u32> {
         match self.state {
             PowerState::A0 => Some(10),
+            // The FPGA still wants our attention! Come back soon!
+            _ if self.is_seq_irq_asserted() => Some(10),
             // we are hoping that a VRM fault will be clearable soon...
             _ if self.vcore.is_still_faulted() => Some(100),
             PowerState::A0PlusHP => Some(1000),
@@ -1018,6 +1020,10 @@ impl ServerImpl {
             }
         };
     }
+
+    fn is_seq_irq_asserted(&self) -> bool {
+        self.sys.gpio_read(SEQ_IRQ) == 0
+    }
 }

 impl idl::InOrderSequencerImpl for ServerImpl {
@@ -1096,17 +1102,32 @@ impl NotificationHandler for ServerImpl {
     }

     fn handle_notification(&mut self, bits: userlib::NotificationBits) {
-        if bits.check_notification_mask(notifications::SEQ_IRQ_MASK) {
+        // Check the actual status of the GPIO pin to determine if we must
+        // handle the sequencer IRQ, rather than the status of the notification
+        // from the EXTI interrupt.
+        if self.is_seq_irq_asserted() {
             let state = self.log_state_registers();
             ringbuf_entry!(Trace::SequencerInterrupt {
                 our_state: self.state,
                 seq_state: state.seq,
             });

-            // Read the IFR register and handle any pending interrupts until the
-            // SEQ_IRQ signal is deasserted (it's active low).
-            while self.sys.gpio_read(SEQ_IRQ) == 0 {
+            // Read the IFR register and handle any pending interrupts. We will
+            // loop a few times here in case additional bits are set whilst we
+            // were handling previous ones, but only do this a few times now.
+            // While it may look like we will leave any IRQs that come in during
+            // the third attempt unhandled, we will set a very short timer
+            // interval if the IRQ line is still asserted, so we'll come back
+            // and continue trying to handle them in a moment.
+            //
+            //
+            // N.B. that 3 is chosen completely arbitrarily
+            for _ in 0..3 {
                 self.handle_sequencer_interrupt();
+                if !self.is_seq_irq_asserted() {
+                    // We're done here!
+                    break;
+                }
             }
         }
```

[^1]: which i've still got to go actually test...

File: drv/cosmo-seq-server/src/vcore.rs (hunk 4 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/vcore.rs:107]: Per the PMBus specification:

> This bit is asserted if the unit is not providing power to
> the output, regardless of the reason, including simply
> not being enabled.
>
> --- _PMBus Specification, Part II, Version 1.3.1_, § 17.2 (p. 92)

So, this would be set if we are in a state where the output rail is not enabled, whether because the FPGA has de-asserted the ENABLE pin, because we have faulted, or because Hubris has sent an I2C command to turn the thing off.[^1]

The FPGA de-asserting the enable pin might also implicitly clear the fault, but I was not completely sure, so I figured it was safer to just mask out the bit when determining if a fault is set. This is somewhat defensive programming but I figured it was worth just doing the most correct thing here.

[^1]: Which we don't presently do on Gimlet, but we do do on Cosmo.

File: drv/cosmo-seq-server/src/main.rs (hunk 2 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:994]: ah, yeah, so it does --- i thought it only did that when we aren't already in the requested state. i can remove this one...but, to be honest, it's a bit weird that we set the state to A0Reset here and then expect host_sp_comms to set it _again.

File: drv/cosmo-seq-server/src/main.rs (hunk 3 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:1177]: Testing this out, I think it does seem to work properly so I'm going to move forwards with this change, possibly with some additional ringbuf

File: drv/cosmo-seq-server/src/main.rs (hunk 2 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:994]: hm, wait: won't the subsequent call to `set_state` from `host_sp_comms` take us from `A0Reset` to `A2` (and then back to `A0`)? so this ringbuf entry is not redundant, as the transition to `A0Reset` would otherwise not be recorded?

**Comment by hawkw** [comment]
Ah, the loopy code behaves a bit oddly with the reset/pwrok IRQs, as it doesn't clear `amd_pwrok_fedge`/`amd_rstn_fedge` IFR bits or mask them out in the IER:

```
  44 1104       10        1 SequencerInterrupt { our_state: A0PlusHP, seq_state: Ok(Done) }
  45  832       10        1 SequencerIfr(IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: false, amd_pwrok_fedge: false, amd_rstn_fedge: true, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: true, vr_v3p3_sys_to_fpga1_alert: true, vr_v5p0_sys_to_fpga1_alert: true, v0p96_nic_to_fpga1_alert: true, pwr_cont1_to_fpga1_alert: false, pwr_cont2_to_fpga1_alert: false, pwr_cont3_to_fpga1_alert: false })
  46  936       10        1 ResetCounts { rstn: 0x0, pwrokn: 0x0 }
  47  832       10        1 SequencerIfr(IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: false, amd_pwrok_fedge: false, amd_rstn_fedge: true, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: true, vr_v3p3_sys_to_fpga1_alert: true, vr_v5p0_sys_to_fpga1_alert: true, v0p96_nic_to_fpga1_alert: true, pwr_cont1_to_fpga1_alert: false, pwr_cont2_to_fpga1_alert: false, pwr_cont3_to_fpga1_alert: false })
  48  936       10        1 ResetCounts { rstn: 0x0, pwrokn: 0x0 }
  49  832       10        1 SequencerIfr(IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: false, amd_pwrok_fedge: false, amd_rstn_fedge: true, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: true, vr_v3p3_sys_to_fpga1_alert: true, vr_v5p0_sys_to_fpga1_alert: true, v0p96_nic_to_fpga1_alert: true, pwr_cont1_to_fpga1_alert: false, pwr_cont2_to_fpga1_alert: false, pwr_cont3_to_fpga1_alert: false })
  50  936       10        1 ResetCounts { rstn: 0x0, pwrokn: 0x0 }
  51  556       10        1 SetState { prev: Some(A0Reset), next: A2, why: CpuReset, now: 0xf2e35 }
```

So, it just loops thrice, which is gross.

**Comment by hawkw** [comment]
0c64525e41a53b7453ed59b95a1e25bdd3cbc680 makes the `amd_rstn_fedge`/`amd_pwrok_fedge` IRQs do the correct thing.

```
   2  530        5    18396 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(NicReset) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
   3 1114        5        1 SequencerInterrupt { our_state: A0, seq_state: Ok(Done) }
   4  830        5        1 SequencerIfr(IfrView { fanfault: false, thermtrip: false, smerr_assert: false, a0mapo: false, nicmapo: false, amd_pwrok_fedge: false, amd_rstn_fedge: true, fan_central_hsc_alert: false, fan_east_hsc_alert: false, fan_west_hsc_alert: false, ibc_alert: false, m2_hsc_alert: false, nic_hsc_alert: false, v12_ddr5_abcdef_hsc_alert: false, v12_ddr5_ghijkl_hsc_alert: false, v12_mcio_a0hp_hsc_alert: false, main_hsc_alert: false, vr_v1p8_sys_to_fpga1_alert: true, vr_v3p3_sys_to_fpga1_alert: true, vr_v5p0_sys_to_fpga1_alert: true, v0p96_nic_to_fpga1_alert: true, pwr_cont1_to_fpga1_alert: false, pwr_cont2_to_fpga1_alert: false, pwr_cont3_to_fpga1_alert: false })
   5  934        5        1 ResetCounts { rstn: 0x1, pwrokn: 0x0 }
   6  979        5        1 SetState { prev: Some(A0), next: A0Reset, why: CpuReset, now: 0x28da78 }
   7  556        5        1 SetState { prev: Some(A0Reset), next: A2, why: CpuReset, now: 0x28da78 }
   8  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Disabling) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(SafeDisable) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
   9  530        5        2 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Idle) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Idle) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  10  556        5        1 SetState { prev: Some(A2), next: A0, why: CpuReset, now: 0x28ee0b }
  11  530        5       84 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(GroupAPgAndWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  12  530        5       20 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(EnableGrpA) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(RtcClkWait) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  13  530        5        2 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Sp5FinalCheckpoint) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(WaitPwrok) }, nic_api_status: NicApiStatusView { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Idle) } }
  14  530        5        1 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(EnablePower) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(WaitForPgs) } }
  15  630        5        1 Coretype { coretype0: true, coretype1: false, coretype2: true, sp5r1: true, sp5r2: false, sp5r3: false, sp5r4: false }
  16  530        5    13396 RegStateValues { seq_api_status: SeqApiStatusView { a0_sm: Ok(Done) }, seq_raw_status: SeqRawStatusView { hw_sm: Ok(Done) }, nic_api_status: NicApiStatusView { nic_sm: Ok(NicReset) }, nic_raw_status: NicRawStatusView { hw_sm: Ok(Done) } }
```

This is with a Real Life Actual Triple Fault triggered via https://github.com/oxidecomputer/illumos-gate/tree/tripfault, rather than poking the sequencer FPGA IGR register into pretending the reset pin was asserted:

```console
eliza@alfred ~ $ pfexec humility qspi -D /staff/andy/tripfault/cosmo.rom
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
humility: erased 9.81MB in 35 seconds
humility: hashed 32.00MB, wrote 9.81MB in 6 minutes
eliza@alfred ~ $ pfexec humility hiffy -c Sequencer.set_state -a state=A0
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP
Sequencer.set_state() => Changed
eliza@alfred ~ $ pfexec humility console-proxy attach
humility: WARNING: archive in environment variable overriding archive in environment file
humility: attached to 1fc9:0143:XJACFXSEKTQJS via CMSIS-DAP

Oxide Pico Host Boot Loader
Config {
    cons:   Uart(fedc9000),
    loader: 0x7f200000..0x7fff0000
    pageroot: P4KA(0x7f209000),
}
Decompressing cpio archive to 0x77200000..0x7f200000...Done.
jumping into kernel...
Oxide board Cosmo -- BRH-C1
Waiting for PSP...ready (2902935510 ticks)
Loading kmdb...
Socket 0 IO die 0: SMU Version: 94.125.0
MPIO Firmware Version: 0x01.0x00.0x1c.0x00
ucode: selected AMD microcode updater
cpu0: microcode has been updated from version 0xb002141 to 0xb002161

Welcome to kmdb
Loaded modules: [ unix krtld genunix ]
[0]> hacky_induce_triple_fault::call
```

File: drv/cosmo-seq-server/src/main.rs (hunk 3 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:1177]: a339911630cf518631e94b4538d1cf5024f1c1e2 changed the loop to be for a small, fixed number of iterations, and we now set a timer to come back to check again if the IRQ is still asserted after that many iterations. This way we shouldn't hot loop and starve other lower-priority tasks if some IRQ just isn't clearing for whatever reason.

File: drv/cosmo-seq-server/src/main.rs (hunk 2 above)
Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:994]: looking at the ringbuf in https://github.com/oxidecomputer/hubris/pull/2390#issuecomment-3922812819, i think we should keep this, as it indicates when the transition from A0 -> A0Reset occurred, which was previously not something we would record at all. the subsequent call from `host_sp_comms` does indeed transition us from `A0Reset` to `A2`, so if we didn't record this one in the IRQ, we would never write down that the A0Reset transition happened.

File: drv/cosmo-seq-server/src/main.rs [hunk 6]
```diff
@@ -1022,8 +1106,33 @@ impl NotificationHandler for ServerImpl {
     }
 
     fn handle_notification(&mut self, bits: userlib::NotificationBits) {
-        if bits.check_notification_mask(notifications::SEQ_IRQ_MASK) {
-            self.handle_sequencer_interrupt();
+        // Check the actual status of the GPIO pin to determine if we must
+        // handle the sequencer IRQ, rather than the status of the notification
+        // from the EXTI interrupt.
+        if self.is_seq_irq_asserted() {
```
Comment (labbott) [inline drv/cosmo-seq-server/src/main.rs:1151]: Can you add a few more words about why we do this here or at least an explanation of why `bits.check_notification_mask(notifications::SEQ_IRQ_MASK)` is insufficient?

Comment (hawkw) [reply drv/cosmo-seq-server/src/main.rs:1151]: Yeah, I was hoping the subsequent comment would explain this sufficiently:
https://github.com/oxidecomputer/hubris/blob/234abbf97d64bacabd9bc81ac8369ce9078ee63a/drv/cosmo-seq-server/src/main.rs#L1131-L1144

...but I realize that it kind of leaves the overall theory behind this implicit. I've combined them into one bigger comment that attempts to explain the whole situation here, beginning with "EXTI can't generate level-triggered interrupts". What do you think of https://github.com/oxidecomputer/hubris/pull/2390/changes/76212417849e953a6b65a4c61f4135ef9c326817 and github.com/oxidecomputer/hubris/pull/2390/commits/cb992777c7f892488bf9a1d1674643970fb75bf1 ?

https://github.com/oxidecomputer/hubris/blob/cb992777c7f892488bf9a1d1674643970fb75bf1/drv/cosmo-seq-server/src/main.rs#L1119-L1176

Comment (labbott) [reply drv/cosmo-seq-server/src/main.rs:1151]: mentioned this in chat but this is great!
