### PR TITLE
Sidecar sequencer: adjust VID polling loop

### LINKED ISSUE #2292: sidecar: Increased frequency of `VidAckTimeout` errors during sequencing
Twice in the last week I've seen Sidecars fail to sequence to A0 during an initial power on to perform loopback test in manufacturing. A `humility hiffy -c Sequencer.clear_tofino_seq_error` allows the system to retry and both times it then sequences normally.

A ringbuf of a faild sequence:
```
aaron@sam ~ $ pfexec humility -p 0483:3754:0039001D4741500920383733 -a /data/local/images/sidecar/d/sp/build-sidecar-d-image-default-v1.0.49.zip ringbuf sequencer
humility: attached to 0483:3754:0039001D4741500920383733 via ST-Link V3
humility: ring buffer drv_oxide_vpd::__RINGBUF in sequencer:
humility: ring buffer drv_packrat_vpd_loader::__RINGBUF in sequencer:
humility: ring buffer drv_sidecar_seq_server::__RINGBUF in sequencer:
 NDX LINE      GEN    COUNT PAYLOAD
   0  849        1        1 FpgaInit
   1  857        1        1 LoadingFpgaBitstream
   2  902        1        1 MainboardControllerId(0x1de5bae)
   3  916        1        1 MainboardControllerChecksum(0x6407475e)
   4  948        1        1 MainboardControllerVersion(0x283)
   5  949        1        1 MainboardControllerSha(0x3c8d1c33)
   6  950        1        1 FpgaInitComplete
   7   31        1        1 LoadingClockConfiguration
   8  975        1        1 ClockConfigurationComplete
   9  226        1        1 FrontIOBoardPowerEnable(true)
  10  243        1        1 FrontIOBoardPowerGood
  11  980        1        1 FrontIOBoardPresent
  12   81        1        1 LoadingFrontIOControllerBitstream { fpga_id: 0x0 }
  13   91        1        1 FrontIOControllerIdent { fpga_id: 0x0, ident: 0x1deaa55 }
  14   98        1        1 FrontIOControllerChecksum { fpga_id: 0x0, checksum: [ 0xd4, 0xaa, 0x2a, 0x16 ], expected: [ 0xd4, 0xaa, 0x2a, 0x16 ] }
  15   81        1        1 LoadingFrontIOControllerBitstream { fpga_id: 0x1 }
  16   91        1        1 FrontIOControllerIdent { fpga_id: 0x1, ident: 0x1deaa55 }
  17   98        1        1 FrontIOControllerChecksum { fpga_id: 0x1, checksum: [ 0xd4, 0xaa, 0x2a, 0x16 ], expected: [ 0xd4, 0xaa, 0x2a, 0x16 ] }
  18  337        1        1 TofinoSequencerTick(LatchOffOnFault, A2 { error: None })
  19  152        1        1 FanModuleLedUpdate(Zero, On)
  20  152        1        1 FanModuleLedUpdate(One, On)
  21  152        1        1 FanModuleLedUpdate(Two, On)
  22  152        1        1 FanModuleLedUpdate(Three, On)
  23  337        1        3 TofinoSequencerTick(LatchOffOnFault, A2 { error: None })
  24  243        1        1 FrontIOBoardPowerGood
  25  326        1        1 FrontIOBoardPhyPowerEnable(true)
  26  548        1        1 FrontIOBoardPhyOscGood
  27  337        1        1 TofinoSequencerTick(LatchOffOnFault, A2 { error: None })
  28   81        1        1 TofinoPowerUp
  29  794        1        1 TofinoSequencerError(SequencerTimeout)
  30  279        1        1 TofinoSequencerAbort { state: InPowerUp, step: AwaitVidAck, error: VidAckTimeout }
  31  337        1     1566 TofinoSequencerTick(LatchOffOnFault, A2 { error: VidAckTimeout })
```

We recently moved from v1.0.35 to v1.0.49 for initial manufacturing programming. I'm curious if we are perhaps doing something faster than we did before which is exposing a poor assumption somewhere.

### PR DESCRIPTION
**Pull request by Aaron-Hartwig**
In practice once the SP starts the A2->A0 sequencing we may not see a valid VID until something around 50-175ms after it begins. That timing is driven by waiting to see power good from 6 different power supplies (sequenced serially), power on reset delay (when the FPGA starts is VID ack counter), and then a VID valid delay (when the FPGA tells the SP it has a valid VID). The FPGA needs to get a VID ack within 200ms of releasing the Tofino reset or it will turn everything off to protect the chip. 

The previous looping mechanism would sample once at 25ms (too early), again at 75ms (maybe valid), and then one final time at 150ms (also maybe valid). This left some open window where VID valid could be asserted after the final poll but the SP will already have returned a `SequencerTimeout` error. I've adjusted the looping mechanism to poll every 50 ms up to 8 times (400 ms total). In practice the latest we could have a valid VID is ~350ms after starting sequencing, so this covers the full window and ensures we try to sample at some point during the valid window.

Fixes #2292

### CODE REVIEW

File: drv/sidecar-seq-server/src/tofino.rs [hunk 1]
```diff
@@ -84,11 +84,12 @@ impl Tofino {
         self.abort_reported = false;
         self.sequencer.set_enable(true)?;
 
-        // Wait for the VID to become valid, retrying if needed.
-        for i in 1..4 {
+        // Wait for the VID to become valid, retrying as needed.
+        for i in 1..=8 {
```
Comment (mkeeter) [inline drv/sidecar-seq-server/src/tofino.rs]: Nit: it would be more idiomatic to do
```suggestion
        for i in 0..8 {
```
