### PR TITLE
Make `apob_lock` allowed on Gimlet

### LINKED ISSUE #2289: `host-sp-comms` failed to get MAC addresses
On `BRM42220026`, IPCC failed to get MAC addresses.

This is a Gimlet C running the stock 1.50 release.

There are a bunch of `host_sp_comms` crash dumps:

```
matt@castle ~ $ humility --ip=fe80::aa40:25ff:fe04:341%5 -a build-gimlet-c-image-default.zip dump --list
humility: connecting to fe80::aa40:25ff:fe04:341%5
humility: using UDP dump agent
AREA TASK                  TIME       SIZE
   0 host_sp_comms         114277     31356
   8 host_sp_comms         114357     30812
  16 host_sp_comms         114437     30824
  24 host_sp_comms         114517     30832
  32 host_sp_comms         114597     30816
  40 host_sp_comms         114677     30820
  48 host_sp_comms         114757     30812
  56 host_sp_comms         114837     30808
  64 host_sp_comms         114917     30808
```

`host_sp_comms` is apparently being murdered by `hf`:
```
matt@castle ~ $ humility -d hubris.core.host_sp_comms.8 tasks
humility: attached to dump
system time = 114917
ID TASK                       GEN PRI STATE
17 host_sp_comms                8   8 FAULT: reply fault: task id #14/gen0, reason BadMessageContents (was: wait: reply from hf/gen0)
```

This is all weird, more to come (opening the issue now to get a ticket number)

### PR DESCRIPTION
**Pull request by mkeeter**
`host-sp-comms` always calls `apob_lock` when it receives a message associated with the later stages of boot (e.g. getting MAC addresses).  Unfortunately, the Gimlet host flash task would kill it for this impertinence.

Fixes #2289

### CODE REVIEW

File: drv/gimlet-hf-server/src/main.rs [hunk 1]
```diff
@@ -944,7 +944,7 @@ impl idl::InOrderHostFlashImpl for ServerImpl {
         &mut self,
         _: &RecvMessage,
     ) -> Result<(), RequestError<core::convert::Infallible>> {
-        Err(RequestError::Fail(ClientError::BadMessageContents))
+        Ok(()) // tautologically true
```
Comment (labbott) [inline drv/gimlet-hf-server/src/main.rs]: Maybe a longer comment here about why we allow `apob_lock` but nothing else?

Comment (mkeeter) [reply drv/gimlet-hf-server/src/main.rs]: Sure, done
