### PR TITLE
stm32xx-gpio-common: fix another glitch

### LINKED ISSUE #1824: I2C is generating 600-750ns glitches, and it should feel bad about this.
This is another episode in the hunt for the Gimlet Disk Wumpus. See also #1821 #1822 #1823.

**tl;dr:** we're glitching the data lines on I2C again, and since this violates setup/hold, devices can respond to this in arbitrarily annoying ways.

Example trace:

2024-07-12-144459_3472x1547_scrot

This is just after we stop the bus reset process (which we started for no obvious reason, see #1823) and resume normal service. We are generating ~680ns negative glitches on both lines, which means that when we reconfigure the pins, we're taking them through low-state push-pull at least briefly on their way back to peripheral-controlled open-drain.

This event is not unique; I see a couple of glitches per minute on average in otherwise working Gimlet traces. (I _think_ they are all related to bus resets.)

These glitches are lengthy enough to bypass the I2C standard glitch filter (50ns), but short enough that they violate the I2C spec's setup and hold requirements. (They're also illegal in the protocol state machine, but, so are a lot of things.) This could potentially trigger metastability or misbehavior of devices on the I2C bus.

We had behavior like this up until February 2023 which was resulting in bus lockups, discussed in #1126, so I would assume that this could cause bus lockups.

### PR DESCRIPTION
**Pull request by cbiffle**
My original fix only made a difference when switching _into_ Alternate mode. In the relatively common case of switching _out of_ Alternate into e.g. Analog or Input (to tristate the pin), code usually uses a utility wrapper that passes AF0 to gpio_configure_raw... and even with the fix in place, we'd update AFRx to AF0 before changing MODER.

Which is the right thing to do if you're going _to_ Alternate, but not vice versa.

So, we got brief glitches to AF0 (which in practice on most pins means pulled to ground) when attempting to tristate pins.

It's possible that we need to revisit this API, which is arguably overly clever. But for now, this commit changes the logic so we don't update AFRx unless relevant.

Fixes #1824 (again).

### CODE REVIEW

File: drv/stm32xx-gpio-common/src/server.rs [hunk 1]
```diff
@@ -162,19 +162,33 @@ impl<T: GpioPeriph> AnyGpioPeriph for T {
...
+        // Only update the alternate fields mux if the mode will be Alternate
+        // when we're done with it. This avoids a glitch in resetting the mux if
+        // switching from Alternate _to_ something else. For the other two
+        // cases:
+        // - Switching between Alternate settings is as glitch-free as is
+        //   feasible in the hardware (though you might want to consider going
+        //   through Analog anyway).
+        //
+        // - Switching _to_ Alternate from a different mode updates the mux
+        //   before MODER, so the update timing is immaterial.
```
Comment (hawkw) [inline drv/stm32xx-gpio-common/src/server.rs:177]: thanks for including this!

Comment (cbiffle) [reply drv/stm32xx-gpio-common/src/server.rs:177]: Every time I have to re-fix this bug, the comments will get longer. For better or worse.
